########################
# SPRING CONFIG GLOBAL #
########################

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  profiles:
  - local
  - dev
  - prod
  active:
    - local
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: skillupdb
  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/skillupdb
    username: postgres
    password: skilluppwd
    
logging:
  pattern:
    level: WARN
